// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMgYkvB8uwa1xUV-DlEEYsvnVflWrExUY',
    appId: '1:98712728186:web:bc3e5226fdddcad54fc1c3',
    messagingSenderId: '98712728186',
    projectId: 'flutterchatapp-a79d4',
    authDomain: 'flutterchatapp-a79d4.firebaseapp.com',
    storageBucket: 'flutterchatapp-a79d4.appspot.com',
    measurementId: 'G-635JFS5C5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNsl0ur_BvmfZVCg6Sz73hknFcRv4Kraw',
    appId: '1:98712728186:android:7b9269220952e5a54fc1c3',
    messagingSenderId: '98712728186',
    projectId: 'flutterchatapp-a79d4',
    storageBucket: 'flutterchatapp-a79d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlcp6r4Q2dVd8XVSH2zm1s_xZYu7yV97Y',
    appId: '1:98712728186:ios:afe78b71c57c60b64fc1c3',
    messagingSenderId: '98712728186',
    projectId: 'flutterchatapp-a79d4',
    storageBucket: 'flutterchatapp-a79d4.appspot.com',
    iosBundleId: 'com.t1n0o69.popeepapp',
  );
}
